//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	lakom "github.com/gardener/gardener-extension-shoot-lakom-service/pkg/apis/lakom"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakomConfig) DeepCopyInto(out *LakomConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(lakom.ScopeType)
		**out = **in
	}
	if in.PublicKeysSecretReference != nil {
		in, out := &in.PublicKeysSecretReference, &out.PublicKeysSecretReference
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakomConfig.
func (in *LakomConfig) DeepCopy() *LakomConfig {
	if in == nil {
		return nil
	}
	out := new(LakomConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakomConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
