# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
  {{ toYaml .Values.cosign | nindent 4 }}
