# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.global.kubeconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-target-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  kubeconfig: {{ .Values.global.kubeconfig | b64enc }}
{{- end }}
