version = 1
SPDX-PackageName = "Gardener gardener-extension-shoot-lakom-service"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/gardener-extension-shoot-lakom-service"

[[annotations]]
path = [".github/**", ".gitignore", ".golangci.yaml.in", ".github/dependabot.yaml", "CODEOWNERS", "VERSION", "OWNERS", "OWNERS_ALIASES", "charts/gardener-extension-shoot-lakom-service/.helmignore", "charts/gardener-extension-shoot-lakom-service/templates/_helpers.tpl", "charts/gardener-extension-shoot-lakom-admission/charts/application/.helmignore", "charts/gardener-extension-shoot-lakom-admission/charts/application/templates/_helpers.tpl", "charts/gardener-extension-shoot-lakom-admission/charts/runtime/.helmignore", "charts/gardener-extension-shoot-lakom-admission/charts/runtime/templates/_helpers.tpl", "charts/lakom/.helmignore", "charts/lakom/charts/runtime/templates/_helpers.tpl", "config/lakom/cosign/password", "example/extension/**", "example/controller-registration.yaml", "example/extension.yaml", "local-setup/.gitignore", "go.mod", "go.sum", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/**", "**.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "pkg/lakom/utils/cosign_utils.go"
precedence = "aggregate"
SPDX-FileCopyrightText = ["Copyright 2021 The Sigstore Authors.", "Modifications Copyright 2022 SAP SE or an SAP affiliate company and Gardener contributors"]
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "hack/cherry-pick-pull.sh"
precedence = "aggregate"
SPDX-FileCopyrightText = ["Copyright 2015 The Kubernetes Authors.", "Modifications Copyright 2021 SAP SE or an SAP affiliate company and Gardener contributors"]
SPDX-License-Identifier = "Apache-2.0"
