apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example

patches:
- patch: |
    - op: replace
      path: /providerConfig/values/image
      value: local-skaffold/gardener-extension-shoot-lakom-service
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: shoot-lakom-service
- path: patch-imagevector-overwrite.yaml
