{{- if .Values.global.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-extension-shoot-lakom-service-admission-kubeconfig
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.global.kubeconfig | b64enc }}
{{- end }}
