# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

gardener:
  virtualCluster:
    enabled: true
    serviceAccount: {}
#     name: gardener-extension-shoot-lakom-admission
#     namespace: kube-system
