# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

---
images:
- name: lakom
  sourceRepository: github.com/gardener/gardener-extension-shoot-lakom-service
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/lakom

