# SPDX-FileCopyrightText: Copyright Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: extension-{{ include "name" . }}-lakom
spec:
  filters:
  - parser:
      keyName: log
      parser: extension-{{ include "name" . }}-lakom-parser
      reserveData: true
  match: kubernetes.*extension-shoot-lakom-service*lakom*
