apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-shoot-lakom-service
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    extension:
      policy: Always
