# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the admission controller of gardener-extension-shoot-lakom
name: gardener-extension-shoot-lakom-admission
version: 0.1.0
