name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    with:
      mode: ${{ inputs.mode }}
      version-commit-callback-action-path: .github/actions/prepare-release
    permissions:
      contents: read

  oci-images:
    name: Build OCI-Images
    needs:
      - prepare
      - verify
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@master
    strategy:
      matrix:
        args:
          - name: gardener-extension-shoot-lakom-service
            target: gardener-extension-shoot-lakom-service
            oci-repository: gardener/extensions/shoot-lakom-service
          - name: lakom
            target: lakom
            oci-repository: gardener/extensions/lakom
          - name: gardener-extension-shoot-lakom-admission
            target: gardener-extension-shoot-lakom-admission
            oci-repository: gardener/extensions/shoot-lakom-admission
    with:
      name: ${{ matrix.args.name }}
      version: ${{ needs.prepare.outputs.version }}
      target: ${{ matrix.args.target }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: ${{ matrix.args.oci-repository }}
      oci-platforms: linux/amd64,linux/arm64
      extra-tags: latest

  oci-images-summary:
    name: OCI Images Summary
    runs-on: solinas
    needs:
    - oci-images
    if: ${{ always() }}  # Ensures this job runs even if the matrix partially fails
    permissions:
      contents: read
    steps:
      - name: Fail if OCI matrix failed
        if: ${{ needs.oci-images.result != 'success' }}
        run: exit 1

  helmcharts:
    name: Build Helmcharts
    needs:
      - prepare
      - oci-images
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@master
    strategy:
      matrix:
        args:
          - name: shoot-lakom-service
            dir: charts/gardener-extension-shoot-lakom-service
            oci-repository: charts/gardener/extensions
            ocm-mappings:
              - ref: ocm-resource:gardener-extension-shoot-lakom-service.repository
                attribute: image.repository
              - ref: ocm-resource:gardener-extension-shoot-lakom-service.tag
                attribute: image.tag
          - name: lakom
            dir: charts/lakom
            oci-repository: charts/gardener/extensions
            ocm-mappings:
              - ref: ocm-resource:lakom.repository
                attribute: image.repository
              - ref: ocm-resource:lakom.tag
                attribute: image.tag
          - name: shoot-lakom-admission-application
            dir: charts/gardener-extension-shoot-lakom-admission/charts/application
            oci-repository: charts/gardener/extensions
            ocm-mappings: []
          - name: shoot-lakom-admission-runtime
            dir: charts/gardener-extension-shoot-lakom-admission/charts/runtime
            oci-repository: charts/gardener/extensions
            ocm-mappings:
              - ref: ocm-resource:gardener-extension-shoot-lakom-admission.repository
                attribute: image.repository
              - ref: ocm-resource:gardener-extension-shoot-lakom-admission.tag
                attribute: image.tag

    with:
      name: ${{ matrix.args.name }}
      dir: ${{ matrix.args.dir }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: ${{ matrix.args.oci-repository }}
      ocm-mappings: ${{ toJSON(matrix.args.ocm-mappings) }}

  helmcharts-summary:
    name: Helm Charts Summary
    runs-on: solinas
    needs:
    - helmcharts
    if: ${{ always() }}  # Ensures this job runs even if the matrix partially fails
    permissions:
      contents: read
    steps:
      - name: Fail if Helm Charts matrix failed
        if: ${{ needs.helmcharts.result != 'success' }}
        run: exit 1

  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - uses: actions/checkout@v4
      - uses: gardener/cc-utils/.github/actions/setup-git-identity@master
      - name: run-verify
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          mkdir -p /tmp/blobs.d
          make verify-extended |& tee /tmp/blobs.d/verify-log.txt
          # verify calls `make sast-report`, which generates `gosec-report.sarif`
          tar czf /tmp/blobs.d/gosec-report.tar.gz gosec-report.sarif
          tar czf /tmp/blobs.d/verify-log.tar.gz -C /tmp/blobs.d verify-log.txt
      - name: add-reports-to-component-descriptor
        uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
        with:
          blobs-directory: /tmp/blobs.d
          ocm-resources: |
            - name: gosec-report
              relation: local
              access:
                type: localBlob
                localReference: gosec-report.tar.gz
              labels:
                - name: gardener.cloud/purposes
                  value:
                    - lint
                    - sast
                    - gosec
                - name: gardener.cloud/comment
                  value: |
                    we use gosec (linter) for SAST scans
                    see: https://github.com/securego/gosec
            - name: test-results
              relation: local
              access:
                type: localBlob
                localReference: verify-log.tar.gz
              labels:
                - name: gardener.cloud/purposes
                  value:
                    - test
