on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pullrequest-trusted-helper:
    permissions:
      pull-requests: write
    secrets:
      github-app-secret-key: ${{ secrets.GARDENER_GITHUB_ACTIONS_PRIVATE_KEY }}
    uses: gardener/cc-utils/.github/workflows/pullrequest-trust-helper.yaml@master
    with:
     trusted-teams: default
