# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-kubeconfig
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.kubeconfig | b64enc }}
{{- end }}
